replicaCount: ${replica_count}

clusterName: ${cluster_name}

region: ${region}
vpcId: ${vpc_id}

serviceAccount:
  create: true
  annotations:
     "eks.amazonaws.com/role-arn": ${role_arn}

image:
  tag: ${image_tag}

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/lifecycle
          operator: In
          values:
            - ondemand
