# Always validate the PR title, and ignore the commits
titleOnly: true

# Always validate all commits, and ignore the PR title
commitsOnly: false

# Always validate the PR title AND all the commits
titleAndCommits: false

# Require at least one commit to be valid
# this is only relevant when using commitsOnly: true or titleAndCommits: true,
# which validate all commits by default
anyCommit: false

# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v2.3.0/index.json
# You can override the valid types
types:
  - feat
  - fix
  - improvement
  - enh
  - doc
  - refactor
  - test
  - ci
  - chore

# Allow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns")
# this is only relevant when using commitsOnly: true (or titleAndCommits: true)
allowMergeCommits: false
