image:
  name: hashicorp/terraform:1.8.3
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

cache:
  key: terraform_dir
  paths:
    - $CI_PROJECT_DIR/terraform/layer1-aws/.terraform
    - $CI_PROJECT_DIR/terraform/layer2-k8s/.terraform
    - $CI_PROJECT_DIR/terraform/layer1-aws/.terraform.lock.hcl
    - $CI_PROJECT_DIR/terraform/layer2-k8s/.terraform.lock.hcl

stages:
  - init
  - check

terraform_init:
  stage: init
  script:
    - cd $CI_PROJECT_DIR/terraform/layer1-aws
    - terraform init -backend=false
    - cd $CI_PROJECT_DIR/terraform/layer2-k8s
    - terraform init -backend=false

terraform_format:
  stage: check
  script:
    - terraform fmt -recursive -write=false -check .

terraform_validate:
  stage: check
  script:
    - cd $CI_PROJECT_DIR/terraform/layer1-aws
    - terraform validate -no-color .
    - cd $CI_PROJECT_DIR/terraform/layer2-k8s
    - terraform validate -no-color .

terraform_tflint:
  image:
    name: wata727/tflint
    entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: check
  script:
    - cd $CI_PROJECT_DIR/terraform/layer1-aws
    - tflint --no-color
    - cd $CI_PROJECT_DIR/terraform/layer2-k8s
    - tflint --no-color
