repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.76.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
    - id: terragrunt_fmt
#    - id: terraform_tflint
#    - id: terraform_tfsec
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: detect-aws-credentials
    - id: detect-private-key
