# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "madops-terraform-state-us-east-1"
    dynamodb_table = "madops-terraform-state-us-east-1-layer2-k8s"
    encrypt        = true
    key            = "layer2-k8s/terraform.tfstate"
    region         = "us-east-1"
  }
}
