apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-addons
  namespace: argocd
spec:
  project: k8s-addons
  source:
    repoURL: 'https://github.com/maddevsio/aws-eks-base.git'
    path: argocd/applications
    targetRevision: argocd
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "*"
      kind: "Application"
      namespace: "*"
      jsonPointers:
        # Allow manually disabling auto sync for apps, useful for debugging.
        - /spec/syncPolicy/automated
        # These are automatically updated on a regular basis. Not ignoring last applied configuration since it's used for computing diffs after normalization.
        - /metadata/annotations/argocd.argoproj.io~1refresh
        - /operation
