server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.example.com
  # Configure RBAC
  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow

configs:
  cm:
    application.resourceTrackingMethod: annotation
    kustomize.buildOptions: --enable-helm
  params:
    server.insecure: "true"
    server.log.level: "warn"
    controller.log.level: "warn"
    reposerver.log.level: "warn"

extraObjects: []

global:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists

controller:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
