apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    version: 8.0.14
    releaseName: argocd
    namespace: argocd
    valuesFile: helm-values.yaml
