apiVersion: v1
kind: Secret
metadata:
  name: aws-eks-base
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/maddevsio/aws-eks-base
