enableSpotInterruptionDraining: true
enableRebalanceMonitoring: true

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: eks.amazonaws.com/capacityType
          operator: In
          values:
          - SPOT
        - key: eks.amazonaws.com/nodegroup
          operator: DoesNotExist
