settings:
  clusterName: maddevs-demo-use1
  interruptionQueue: Karpenter-maddevs-demo-use1

controller:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
