name: 'aws-eks-utils'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/aws-eks-utils/Dockerfile'

jobs:
  push_to_registries:
    name: Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker/aws-eks-utils/
          tags: maddevsio/aws-eks-utils:latest
